### ISSUE TITLE
2.1.4 - LagSpikes & Crash maybe Advanced Rocketry 1.7.0-240

### ISSUE THREAD

**Issue by Aringarosa** [W1nter-isHere/FC-Atomic-Space#44]
Hello FC-Team,
I play FC:AC actually at Chapter 3.  As of Chapter 2 i have random Lag spikes and the Instance on my homeserver crash. My Investigation results:

![image](https://user-images.githubusercontent.com/5900536/119247248-41463a80-bb88-11eb-9a8f-865a569b50cf.png)

It look like AdvancedRocketry 1.7.0-240 causes the Spikes. In combination with my Crash logs:

> Time: 5/20/21 10:59 AM
> Description: Watching Server
> 
> java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
>         at java.io.FileDescriptor.sync(Native Method)
>         at zmaster587.advancedRocketry.dimension.DimensionManager.saveDimensions(DimensionManager.java:667)
>         at zmaster587.advancedRocketry.event.PlanetEventHandler.worldSaveEvent(PlanetEventHandler.java:576)
>         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2290_PlanetEventHandler_worldSaveEvent_Save.inv
> oke(.dynamic)
>         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
>         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
>         at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1008)
>         at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408)
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:691)
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
>         at java.lang.Thread.run(Thread.java:748)

Which indicates that AR is causing the extreme Server Tick.
On top the server logs every minute a overload warning.

> [03:32:14] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server 
> overloaded? Running 3546ms behind, skipping 70 tick(s)
> [03:32:57] [Server thread/INFO] [gamestages]: Saved 3 stages for Aringaros.
> [03:33:42] [Server thread/INFO] [gamestages]: Saved 3 stages for Aringaros.
> [03:34:27] [Server thread/INFO] [gamestages]: Saved 3 stages for Aringaros.
> [03:34:30] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2552ms behind, skipping 51 tick(s)
> [03:35:14] [Server thread/INFO] [gamestages]: Saved 3 stages for Aringaros.
> [03:35:16] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3126ms behind, skipping 62 tick(s)
> [03:35:32] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3065ms behind, skipping 61 tick(s)
> [03:36:00] [Server thread/INFO] [gamestages]: Saved 3 stages for Aringaros.
> [03:36:04] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3607ms behind, skipping 72 tick(s)
> [03:36:47] [Server thread/INFO] [gamestages]: Saved 3 stages for Aringaros.
> [03:36:55] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 7763ms behind, skipping 155 tick(s)
> [03:37:38] [Server thread/INFO] [gamestages]: Saved 3 stages for Aringaros.
> [03:38:23] [Server thread/INFO] [gamestages]: Saved 3 stages for Aringaros.
> [03:39:08] [Server thread/INFO] [gamestages]: Saved 3 stages for Aringaros.
> [03:39:11] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3527ms behind, skipping 70 tick(s)
> [03:39:54] [Server thread/INFO] [gamestages]: Saved 3 stages for Aringaros.
> [03:40:39] [Server thread/INFO] [gamestages]: Saved 3 stages for Aringaros.
> [03:40:44] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4802ms behind, skipping 96 tick(s)

Additional Mod used: Laggoggles Server / Client Side.

Greetings Ringo

**Comment by Aringarosa** [comment]
Ashes on my head ... How mistakes are presented. The hard drive is just dying a hero's death.
